import { RouteSeatTypeDetail } from './roteSeatType.class';
import { DPPrims } from './dpprims.class';
import { Fare } from './fare.class';
import { BPPrims } from './bpprims.class';
export class Onwardflight {
        origin: string;
        rating: string;
        DepartureTime: string;
        cancellationPolicy: string;
        farebasis: string;
        BusServiceID: string;
        seat: string;
        duration: string;
        qtype: string;
        srtFee: number;
        skey: string;
        busCondition: string;
        src_voyager_id: string;
        levyFee: number;
        destination: string;
        BPPrims: BPPrims;
        amenities: string;
        src_vendor_id: string;
        dest_voyager_id: string;
        gps: string;
        fare: Fare;
        dst_vendor_id: string;
        OperatorID: string;
        DPPrims: DPPrims;
        mTicket: string;
        row_type: string;
        BusType: string;
        RouteSeatTypeDetail: RouteSeatTypeDetail;
        partialCancellationAllowed: string;
        idRequired: string;
        ServiceName: string;
        busCompany: string;
        TravelsName: string;
        tbrequired: string;
        RouteID: string;
        ArrivalTime: string;
        depdate: Date;
        ugcid: string;
        arrdate: Date;
    }