//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 01:19:06 PM CST 
//


package com.ibm.iis.igc.asset_type_descriptor;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Class complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Class">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.ibm.com/iis/igc/asset-type-descriptor}Labeling"/>
 *         &lt;group ref="{http://www.ibm.com/iis/igc/asset-type-descriptor}PluralLabeling"/>
 *         &lt;element name="storage" type="{http://www.ibm.com/iis/igc/asset-type-descriptor}ClassStorage" minOccurs="0"/>
 *         &lt;element name="headerSection" type="{http://www.ibm.com/iis/igc/asset-type-descriptor}HeaderSection" minOccurs="0"/>
 *         &lt;element name="section" type="{http://www.ibm.com/iis/igc/asset-type-descriptor}Section" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.ibm.com/iis/igc/asset-type-descriptor}Identifying"/>
 *       &lt;attribute name="superClassRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="restCodeName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="containerClassRefs" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="omdClassRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="canHaveImage" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="expandableInLineage" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="dataAccessRole" type="{http://www.ibm.com/iis/igc/asset-type-descriptor}DataAccessRoleEnum" default="Active" />
 *       &lt;attribute name="reportingLevel" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Class", propOrder = {
    "label",
    "pluralLabel",
    "storage",
    "headerSection",
    "section"
})
public class Class {

    @XmlElement(required = true)
    protected Label label;
    @XmlElement(required = true)
    protected Label pluralLabel;
    protected ClassStorage storage;
    protected HeaderSection headerSection;
    protected List<Section> section;
    @XmlAttribute(name = "superClassRef")
    protected String superClassRef;
    @XmlAttribute(name = "restCodeName")
    protected String restCodeName;
    @XmlAttribute(name = "containerClassRefs")
    protected String containerClassRefs;
    @XmlAttribute(name = "omdClassRef")
    protected String omdClassRef;
    @XmlAttribute(name = "canHaveImage")
    protected Boolean canHaveImage;
    @XmlAttribute(name = "expandableInLineage")
    protected Boolean expandableInLineage;
    @XmlAttribute(name = "dataAccessRole")
    protected DataAccessRoleEnum dataAccessRole;
    @XmlAttribute(name = "reportingLevel")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger reportingLevel;
    @XmlAttribute(name = "localId", required = true)
    protected String localId;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link Label }
     *     
     */
    public Label getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link Label }
     *     
     */
    public void setLabel(Label value) {
        this.label = value;
    }

    /**
     * Gets the value of the pluralLabel property.
     * 
     * @return
     *     possible object is
     *     {@link Label }
     *     
     */
    public Label getPluralLabel() {
        return pluralLabel;
    }

    /**
     * Sets the value of the pluralLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Label }
     *     
     */
    public void setPluralLabel(Label value) {
        this.pluralLabel = value;
    }

    /**
     * Gets the value of the storage property.
     * 
     * @return
     *     possible object is
     *     {@link ClassStorage }
     *     
     */
    public ClassStorage getStorage() {
        return storage;
    }

    /**
     * Sets the value of the storage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassStorage }
     *     
     */
    public void setStorage(ClassStorage value) {
        this.storage = value;
    }

    /**
     * Gets the value of the headerSection property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderSection }
     *     
     */
    public HeaderSection getHeaderSection() {
        return headerSection;
    }

    /**
     * Sets the value of the headerSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderSection }
     *     
     */
    public void setHeaderSection(HeaderSection value) {
        this.headerSection = value;
    }

    /**
     * Gets the value of the section property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the section property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Section }
     * 
     * 
     */
    public List<Section> getSection() {
        if (section == null) {
            section = new ArrayList<Section>();
        }
        return this.section;
    }

    public void addSection(Section sec){
    	 if (section != null) {
             section.add(sec);
         }
    }
    /**
     * Gets the value of the superClassRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuperClassRef() {
        return superClassRef;
    }

    /**
     * Sets the value of the superClassRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuperClassRef(String value) {
        this.superClassRef = value;
    }

    /**
     * Gets the value of the restCodeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestCodeName() {
        return restCodeName;
    }

    /**
     * Sets the value of the restCodeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestCodeName(String value) {
        this.restCodeName = value;
    }

    /**
     * Gets the value of the containerClassRefs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerClassRefs() {
        return containerClassRefs;
    }

    /**
     * Sets the value of the containerClassRefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerClassRefs(String value) {
        this.containerClassRefs = value;
    }

    /**
     * Gets the value of the omdClassRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOmdClassRef() {
        return omdClassRef;
    }

    /**
     * Sets the value of the omdClassRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOmdClassRef(String value) {
        this.omdClassRef = value;
    }

    /**
     * Gets the value of the canHaveImage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCanHaveImage() {
        if (canHaveImage == null) {
            return false;
        } else {
            return canHaveImage;
        }
    }

    /**
     * Sets the value of the canHaveImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanHaveImage(Boolean value) {
        this.canHaveImage = value;
    }

    /**
     * Gets the value of the expandableInLineage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isExpandableInLineage() {
        if (expandableInLineage == null) {
            return false;
        } else {
            return expandableInLineage;
        }
    }

    /**
     * Sets the value of the expandableInLineage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExpandableInLineage(Boolean value) {
        this.expandableInLineage = value;
    }

    /**
     * Gets the value of the dataAccessRole property.
     * 
     * @return
     *     possible object is
     *     {@link DataAccessRoleEnum }
     *     
     */
    public DataAccessRoleEnum getDataAccessRole() {
        if (dataAccessRole == null) {
            return DataAccessRoleEnum.ACTIVE;
        } else {
            return dataAccessRole;
        }
    }

    /**
     * Sets the value of the dataAccessRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataAccessRoleEnum }
     *     
     */
    public void setDataAccessRole(DataAccessRoleEnum value) {
        this.dataAccessRole = value;
    }

    /**
     * Gets the value of the reportingLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReportingLevel() {
        return reportingLevel;
    }

    /**
     * Sets the value of the reportingLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReportingLevel(BigInteger value) {
        this.reportingLevel = value;
    }

    /**
     * Gets the value of the localId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalId() {
        return localId;
    }

    /**
     * Sets the value of the localId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalId(String value) {
        this.localId = value;
    }

}
