//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.17 at 01:19:06 PM CST 
//


package com.ibm.iis.igc.asset_type_descriptor;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Descriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Descriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="family" type="{http://www.ibm.com/iis/igc/asset-type-descriptor}Family" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="tree" type="{http://www.ibm.com/iis/igc/asset-type-descriptor}Tree" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="class" type="{http://www.ibm.com/iis/igc/asset-type-descriptor}Class" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="bundleId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Descriptor", propOrder = {
    "family",
    "tree",
    "clazz"
})
public class Descriptor {

    protected List<Family> family;
    protected List<Tree> tree;
    @XmlElement(name = "class", required = true)
    protected List<Class> clazz;
    @XmlAttribute(name = "bundleId", required = true)
    protected String bundleId;

    /**
     * Gets the value of the family property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the family property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFamily().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Family }
     * 
     * 
     */
    public List<Family> getFamily() {
        if (family == null) {
            family = new ArrayList<Family>();
        }
        return this.family;
    }

    
    public void addFamily(Family fam){
      	 if (family != null) {
      		family.add(fam);
           }
      }
    /**
     * Gets the value of the tree property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tree property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTree().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tree }
     * 
     * 
     */
    public List<Tree> getTree() {
        if (tree == null) {
            tree = new ArrayList<Tree>();
        }
        return this.tree;
    }

    
    public void addTree(Tree tr){
   	 if (tree != null) {
            tree.add(tr);
        }
   }

    /**
     * Gets the value of the clazz property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clazz property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClazz().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Class }
     * 
     * 
     */
    public List<Class> getClazz() {
        if (clazz == null) {
            clazz = new ArrayList<Class>();
        }
        return this.clazz;
    }
    
    public void addClazz(Class c){
    	 if (clazz != null) {
             clazz.add(c);
         }
    }

    /**
     * Gets the value of the bundleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBundleId() {
        return bundleId;
    }

    /**
     * Sets the value of the bundleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBundleId(String value) {
        this.bundleId = value;
    }

}
